In [4]:
%pip install skillsnetwork

Collecting skillsnetwork
  Downloading skillsnetwork-0.21.10-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: ipython in /home/codespace/.local/lib/python3.12/site-packages (from skillsnetwork) (9.7.0)
Collecting ipywidgets<=8.1.3 (from skillsnetwork)
  Downloading ipywidgets-8.1.3-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: requests<3,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from skillsnetwork) (2.32.5)
Collecting tqdm<5,>=4 (from skillsnetwork)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: comm>=0.1.3 in /home/codespace/.local/lib/python3.12/site-packages (from ipywidgets<=8.1.3->skillsnetwork) (0.2.3)
Requirement already satisfied: traitlets>=4.3.1 in /home/codespace/.local/lib/python3.12/site-packages (from ipywidgets<=8.1.3->skillsnetwork) (5.14.3)
Collecting widgetsnbextension~=4.0.11 (from ipywidgets<=8.1.3->skillsnetwork)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab-widgets~=3.0.11 (from ipywidgets<=8.1.3->skillsnetwork)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3,>=2->skillsnetwork) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3,>=2->skillsnetwork) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3,>=2->skillsnetwork) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3,>=2->skillsnetwork) (2025.11.12)
Requirement already satisfied: decorator>=4.3.2 in /home/codespace/.local/lib/python3.12/site-packages (from ipython->skillsnetwork) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from ipython->skillsnetwork) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /home/codespace/.local/lib/python3.12/site-packages (from ipython->skillsnetwork) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in /home/codespace/.local/lib/python3.12/site-packages (from ipython->skillsnetwork) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /home/codespace/.local/lib/python3.12/site-packages (from ipython->skillsnetwork) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/codespace/.local/lib/python3.12/site-packages (from ipython->skillsnetwork) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in /home/codespace/.local/lib/python3.12/site-packages (from ipython->skillsnetwork) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /home/codespace/.local/lib/python3.12/site-packages (from ipython->skillsnetwork) (0.6.3)
Requirement already satisfied: wcwidth in /home/codespace/.local/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->skillsnetwork) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/codespace/.local/lib/python3.12/site-packages (from jedi>=0.18.1->ipython->skillsnetwork) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /home/codespace/.local/lib/python3.12/site-packages (from pexpect>4.3->ipython->skillsnetwork) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython->skillsnetwork) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython->skillsnetwork) (3.0.1)
Requirement already satisfied: pure-eval in /home/codespace/.local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython->skillsnetwork) (0.2.3)
Downloading skillsnetwork-0.21.10-py3-none-any.whl (26 kB)
Downloading ipywidgets-8.1.3-py3-none-any.whl (139 kB)
Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 914.9/914.9 kB 34.9 MB/s  0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 47.2 MB/s  0:00:00
Installing collected packages: widgetsnbextension, tqdm, jupyterlab-widgets, ipywidgets, skillsnetwork
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [skillsnetwork]0m [ipywidgets]
Successfully installed ipywidgets-8.1.3 jupyterlab-widgets-3.0.16 skillsnetwork-0.21.10 tqdm-4.67.3 widgetsnbextension-4.0.15

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
%config InlineBackend.figure_formats = ['retina']

import pandas as pd
import seaborn as sns
import skillsnetwork
sns.set()

In [7]:
url = "https://raw.githubusercontent.com/NoorAbdulAziz/Data/main/Ames_Housing_Data1.tsv"

df = pd.read_csv(url, sep='\t')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2931 entries, 0 to 2930
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2931 non-null   int64
 1   PID              2931 non-null   int64
 2   MS SubClass      2931 non-null   int64
 3   MS Zoning        2931 non-null   str
 4   Lot Frontage     2441 non-null   float64
 5   Lot Area         2931 non-null   int64
 6   Street           2931 non-null   str
 7   Alley            198 non-null    str
 8   Lot Shape        2931 non-null   str
 9   Land Contour     2931 non-null   str
 10  Utilities        2931 non-null   str
 11  Lot Config       2931 non-null   str
 12  Land Slope       2931 non-null   str
 13  Neighborhood     2931 non-null   str
 14  Condition 1      2931 non-null   str
 15  Condition 2      2931 non-null   str
 16  Bldg Type        2931 non-null   str
 17  House Style      2931 non-null   str
 18  Overall Qual     2931 non-null   int64
 19  Overall Cond     2931 non-null   int64
 20  Year Built       2931 non-null   int64
 21  Year Remod/Add   2931 non-null   int64
 22  Roof Style       2931 non-null   str
 23  Roof Matl        2931 non-null   str
 24  Exterior 1st     2931 non-null   str
 25  Exterior 2nd     2931 non-null   str
 26  Mas Vnr Type     1156 non-null   str
 27  Mas Vnr Area     2908 non-null   float64
 28  Exter Qual       2931 non-null   str
 29  Exter Cond       2931 non-null   str
 30  Foundation       2931 non-null   str
 31  Bsmt Qual        2851 non-null   str
 32  Bsmt Cond        2851 non-null   str
 33  Bsmt Exposure    2848 non-null   str
 34  BsmtFin Type 1   2851 non-null   str
 35  BsmtFin SF 1     2930 non-null   float64
 36  BsmtFin Type 2   2850 non-null   str
 37  BsmtFin SF 2     2930 non-null   float64
 38  Bsmt Unf SF      2930 non-null   float64
 39  Total Bsmt SF    2930 non-null   float64
 40  Heating          2931 non-null   str
 41  Heating QC       2931 non-null   str
 42  Central Air      2931 non-null   str
 43  Electrical       2930 non-null   str
 44  1st Flr SF       2931 non-null   int64
 45  2nd Flr SF       2931 non-null   int64
 46  Low Qual Fin SF  2931 non-null   int64
 47  Gr Liv Area      2931 non-null   int64
 48  Bsmt Full Bath   2929 non-null   float64
 49  Bsmt Half Bath   2929 non-null   float64
 50  Full Bath        2931 non-null   int64
 51  Half Bath        2931 non-null   int64
 52  Bedroom AbvGr    2931 non-null   int64
 53  Kitchen AbvGr    2931 non-null   int64
 54  Kitchen Qual     2931 non-null   str
 55  TotRms AbvGrd    2931 non-null   int64
 56  Functional       2931 non-null   str
 57  Fireplaces       2931 non-null   int64
 58  Fireplace Qu     1509 non-null   str
 59  Garage Type      2774 non-null   str
 60  Garage Yr Blt    2772 non-null   float64
 61  Garage Finish    2772 non-null   str
 62  Garage Cars      2930 non-null   float64
 63  Garage Area      2930 non-null   float64
 64  Garage Qual      2772 non-null   str
 65  Garage Cond      2772 non-null   str
 66  Paved Drive      2931 non-null   str
 67  Wood Deck SF     2931 non-null   int64
 68  Open Porch SF    2931 non-null   int64
 69  Enclosed Porch   2931 non-null   int64
 70  3Ssn Porch       2931 non-null   int64
 71  Screen Porch     2931 non-null   int64
 72  Pool Area        2931 non-null   int64
 73  Pool QC          13 non-null     str
 74  Fence            572 non-null    str
 75  Misc Feature     106 non-null    str
 76  Misc Val         2931 non-null   int64
 77  Mo Sold          2931 non-null   int64
 78  Yr Sold          2931 non-null   int64
 79  Sale Type        2931 non-null   str
 80  Sale Condition   2931 non-null   str
 81  SalePrice        2931 non-null   int64
dtypes: float64(11), int64(28), str(43)
memory usage: 1.8 MB

In [9]:
df = df.loc[df['Gr Liv Area'] <= 4000,:]
print("Number of rows in the data:", df.shape[0])
print("Number of columns in the data:", df.shape[1])
data = df.copy() # Keep a copy our original data

Number of rows in the data: 2926
Number of columns in the data: 82

In [10]:
# A quick look at the data:
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
2,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
3,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
4,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000

In [14]:
# Get a Pd.Series consisting of all the string categoricals
one_hot_encode_cols = df.dtypes[df.dtypes == object]  # filtering by string categoricals
one_hot_encode_cols = one_hot_encode_cols.index.tolist()  # list of categorical fields

df[one_hot_encode_cols].head().T

Empty DataFrame
Columns: [0, 1, 2, 3, 4]
Index: []

We're going to first do some basic data cleaning on this data:

Converting categorical variables to dummies
Making skew variables symmetric
One-hot encoding the dummy variables:

In [15]:
# Do the one hot encoding
df = pd.get_dummies(df, columns=one_hot_encode_cols, drop_first=True)
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Order,2926.0,1.464294e+03,8.467295e+02,1.0,7.312500e+02,1462.5,2.198750e+03,2.930000e+03
PID,2926.0,7.143288e+08,1.887272e+08,526301100.0,5.284770e+08,535453205.0,9.071801e+08,1.007100e+09
MS SubClass,2926.0,5.738380e+01,4.266706e+01,20.0,2.000000e+01,50.0,7.000000e+01,1.900000e+02
Lot Frontage,2436.0,6.905337e+01,2.275304e+01,21.0,5.800000e+01,68.0,8.000000e+01,3.130000e+02
Lot Area,2926.0,1.011099e+04,7.790972e+03,1300.0,7.438500e+03,9429.0,1.151875e+04,2.152450e+05
Overall Qual,2926.0,6.088175e+00,1.402714e+00,1.0,5.000000e+00,6.0,7.000000e+00,1.000000e+01
Overall Cond,2926.0,5.563568e+00,1.112121e+00,1.0,5.000000e+00,5.0,6.000000e+00,9.000000e+00
Year Built,2926.0,1.971299e+03,3.023803e+01,1872.0,1.954000e+03,1973.0,2.000750e+03,2.010000e+03
Year Remod/Add,2926.0,1.984226e+03,2.086302e+01,1950.0,1.965000e+03,1993.0,2.004000e+03,2.010000e+03
Mas Vnr Area,2903.0,1.007144e+02,1.760041e+02,0.0,0.000000e+00,0.0,1.640000e+02,1.600000e+03
BsmtFin SF 1,2925.0,4.381662e+02,4.379731e+02,0.0,0.000000e+00,370.0,7.330000e+02,2.288000e+03
BsmtFin SF 2,2925.0,4.979043e+01,1.692741e+02,0.0,0.000000e+00,0.0,0.000000e+00,1.526000e+03
Bsmt Unf SF,2925.0,5.589070e+02,4.395516e+02,0.0,2.190000e+02,464.0,8.010000e+02,2.336000e+03
Total Bsmt SF,2925.0,1.046864e+03,4.210380e+02,0.0,7.930000e+02,990.0,1.299000e+03,3.206000e+03
1st Flr SF,2926.0,1.155632e+03,3.766413e+02,334.0,8.760000e+02,1082.5,1.383000e+03,3.820000e+03
2nd Flr SF,2926.0,3.337187e+02,4.258139e+02,0.0,0.000000e+00,0.0,7.020000e+02,1.862000e+03
Low Qual Fin SF,2926.0,4.683185e+00,4.634184e+01,0.0,0.000000e+00,0.0,0.000000e+00,1.064000e+03
Gr Liv Area,2926.0,1.494034e+03,4.861997e+02,334.0,1.126000e+03,1441.5,1.740000e+03,3.820000e+03
Bsmt Full Bath,2924.0,4.305746e-01,5.241048e-01,0.0,0.000000e+00,0.0,1.000000e+00,3.000000e+00
Bsmt Half Bath,2924.0,6.053352e-02,2.441835e-01,0.0,0.000000e+00,0.0,0.000000e+00,2.000000e+00
Full Bath,2926.0,1.564593e+00,5.513904e-01,0.0,1.000000e+00,2.0,2.000000e+00,4.000000e+00
Half Bath,2926.0,3.783322e-01,5.023658e-01,0.0,0.000000e+00,0.0,1.000000e+00,2.000000e+00
Bedroom AbvGr,2926.0,2.853725e+00,8.275996e-01,0.0,2.000000e+00,3.0,3.000000e+00,8.000000e+00
Kitchen AbvGr,2926.0,1.044429e+00,2.142163e-01,0.0,1.000000e+00,1.0,1.000000e+00,3.000000e+00
TotRms AbvGrd,2926.0,6.434381e+00,1.557656e+00,2.0,5.000000e+00,6.0,7.000000e+00,1.400000e+01
Fireplaces,2926.0,5.974026e-01,6.457594e-01,0.0,0.000000e+00,1.0,1.000000e+00,4.000000e+00
Garage Yr Blt,2767.0,1.978082e+03,2.552657e+01,1895.0,1.960000e+03,1979.0,2.002000e+03,2.207000e+03
Garage Cars,2925.0,1.765128e+00,7.597166e-01,0.0,1.000000e+00,2.0,2.000000e+00,5.000000e+00
Garage Area,2925.0,4.719029e+02,2.137820e+02,0.0,3.200000e+02,480.0,5.760000e+02,1.488000e+03
Wood Deck SF,2926.0,9.343199e+01,1.260310e+02,0.0,0.000000e+00,0.0,1.680000e+02,1.424000e+03
Open Porch SF,2926.0,4.717191e+01,6.656099e+01,0.0,0.000000e+00,27.0,7.000000e+01,7.420000e+02
Enclosed Porch,2926.0,2.304306e+01,6.417725e+01,0.0,0.000000e+00,0.0,0.000000e+00,1.012000e+03
3Ssn Porch,2926.0,2.596036e+00,2.515833e+01,0.0,0.000000e+00,0.0,0.000000e+00,5.080000e+02
Screen Porch,2926.0,1.602392e+01,5.612258e+01,0.0,0.000000e+00,0.0,0.000000e+00,5.760000e+02
Pool Area,2926.0,1.892686e+00,3.295865e+01,0.0,0.000000e+00,0.0,0.000000e+00,8.000000e+02
Misc Val,2926.0,4.489440e+01,4.721580e+02,0.0,0.000000e+00,0.0,0.000000e+00,1.550000e+04
Mo Sold,2926.0,6.216336e+00,2.711171e+00,1.0,4.000000e+00,6.0,8.000000e+00,1.200000e+01
Yr Sold,2926.0,2.007792e+03,1.317815e+00,2006.0,2.007000e+03,2008.0,2.009000e+03,2.010000e+03
SalePrice,2926.0,1.804234e+05,7.854403e+04,12789.0,1.295000e+05,160000.0,2.135000e+05,6.250000e+05

Log Transformaing Skew variables

In [1]:
# Create a list of float colums to check for skewing
mask = data.dtypes == float
float_cols = data.columns[mask]

skew_limit = 0.75 # define a limit above which we will log transform
skew_vals = data[float_cols].skew()

NameError: name 'data' is not defined

In [2]:
# Showing the skewed columns
skew_cols = (skew_vals
             .sort_values(ascending=False)
             .to_frame()
             .rename(columns={0:'Skew'})
             .query('abs(Skew) > {}'.format(skew_limit)))

skew_cols

NameError: name 'skew_vals' is not defined